language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-dist

script: 
    - vendor/bin/phpunit tests --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)